---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Config
- type: document
  path: exampleSite/config.toml
  label: Config
  match: "**/*"
- type: document
  path: exampleSite/data/id/team.yml
  label: Team
- type: document
  path: exampleSite/data/id/testimonial.yml
  label: Testimonial
- type: document
  path: exampleSite/data/id/pricing.yml
  label: Pricing
- type: document
  path: exampleSite/data/id/service.yml
  label: Services
- type: document
  path: exampleSite/data/id/portfolio.yml
  label: Portfolio
- type: heading
  label: Content
- type: directory
  path: exampleSite/data
  label: Data
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: exampleSite/content/blog
  label: Blog
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/about
  label: About
  create: all
  match: "**/*"
upload_dir: exampleSite/static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.73.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.73.0
