---
label: Config
hide_body: true
fields:
- type: text
  name: DefaultContentLanguage
  label: DefaultContentLanguage
- type: text
  name: baseURL
  label: baseURL
- type: boolean
  name: defaultContentLanguageInSubdir
  label: defaultContentLanguageInSubdir
- type: boolean
  name: enableGitInfo
  label: enableGitInfo
- type: boolean
  name: enableRobotsTXT
  label: enableRobotsTXT
- type: text
  name: googleAnalytics
  label: googleAnalytics
- type: text
  name: languageCode
  label: languageCode
- type: boolean
  name: pygmentsCodeFences
  label: pygmentsCodeFences
- type: number
  name: summaryLength
  label: summaryLength
- type: text
  name: theme
  label: theme
- type: text
  name: title
  label: title
- type: field_group
  name: Languages
  label: Languages
  fields:
  - type: field_group
    name: id
    label: id
    fields:
    - type: text
      name: dateFormat
      label: dateFormat
    - type: text
      name: footerAboutTitle
      label: footerAboutTitle
    - type: textarea
      name: footerDescription
      label: footerDescription
    - type: text
      name: footerQuicklinkTitle
      label: footerQuicklinkTitle
    - type: text
      name: footerServiceTitle
      label: footerServiceTitle
    - type: text
      name: footerSubscribeTitle
      label: footerSubscribeTitle
    - type: text
      name: home
      label: home
    - type: text
      name: languageCode
      label: languageCode
    - type: file
      name: logo
      label: logo
    - type: boolean
      name: menufixed
      label: menufixed
    - type: text
      name: title
      label: title
    - type: number
      name: weight
      label: weight
    - type: field_group
      name: params
      label: params
      fields:
      - type: field_group
        name: aboutSm
        label: aboutSm
        fields:
        - type: textarea
          name: description
          label: description
        - type: boolean
          name: enable
          label: enable
        - type: text
          name: title
          label: title
      - type: field_group
        name: blog
        label: blog
        fields:
        - type: boolean
          name: enable
          label: enable
        - type: textarea
          name: subtitle
          label: subtitle
        - type: text
          name: title
          label: title
        - type: text
          name: topTitle
          label: topTitle
      - type: field_group
        name: contact
        label: contact
        fields:
        - type: text
          name: address
          label: address
        - type: boolean
          name: enable
          label: enable
        - type: text
          name: facebook
          label: facebook
        - type: text
          name: instagram
          label: instagram
        - type: text
          name: phone
          label: phone
        - type: textarea
          name: subtitle
          label: subtitle
        - type: text
          name: title
          label: title
        - type: text
          name: topTitle
          label: topTitle
      - type: field_group
        name: cta
        label: cta
        fields:
        - type: file
          name: bg
          label: bg
        - type: text
          name: btnText
          label: btnText
        - type: boolean
          name: enable
          label: enable
        - type: textarea
          name: subtitle
          label: subtitle
        - type: text
          name: title
          label: title
      - type: field_group
        name: hero
        label: hero
        fields:
        - type: text
          name: btnText
          label: btnText
        - type: text
          name: btnURL
          label: btnURL
        - type: boolean
          name: button
          label: button
        - type: textarea
          name: description
          label: description
        - type: boolean
          name: enable
          label: enable
        - type: text
          name: heading
          label: heading
        - type: file
          name: videoThumb
          label: videoThumb
        - type: text
          name: videoURL
          label: videoURL
- type: field_group
  name: Params
  label: Params
  fields:
  - type: list
    name: listeLangues
    label: listeLangues
- type: field_group
  name: params
  label: params
  fields:
  - type: field_group
    name: cookies
    label: cookies
    fields:
    - type: boolean
      name: enable
      label: enable
    - type: number
      name: expire_days
      label: expire_days
  - type: text
    name: dateFormat
    label: dateFormat
  - type: file
    name: logo
    label: logo
- type: field_group
  name: menu
  label: menu
  fields:
  - type: list
    name: quicklink
    label: quicklink
  - type: list
    name: service
    label: service
  - type: field_group_list
    name: nav
    label: nav
    fields:
    - type: text
      name: name
      label: name
    - type: text
      name: url
      label: url
    - type: number
      name: weight
      label: weight
